#!/bin/bash

arg1=$1

# Pull in the BOOK_CONFIGS and RECIPE_NAMES
source ./books.txt || exit 1

if [ ! "${arg1}" == "" ]
then
  RECIPE_NAMES=(${arg1})
fi


sassBin="$(npm bin)/sass"

# Try running sass locally (using rbenv). If that does not work then try it globally
if [[ ! $(${sassBin} --version 2>/dev/null) ]]
then
  >&2 echo "ERROR: Could not find sass executable"
  >&2 echo "INFO: Maybe rerun ./script/setup"
  exit 1
fi


for recipeName in "${RECIPE_NAMES[@]}"
do

  sassFile="./recipes/books/${recipeName}/book.scss"
  cssFile="./recipes/output/${recipeName}.css"

  >&2 echo "==> Generating ${cssFile}"

  ${sassBin} ${sassFile} > ${cssFile} || exit 1
done

./script/build-manifest
